name: "Deploy"

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Roda os testes da aplicação"

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Verifica o repositório Git
        uses: actions/checkout@v2

      - name: Instala o node com a versão ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instala as dependências
        run: |
          npm install
      - name: Roda os testes
        run: |
          npm test

  vercel:
    needs: test 
    runs-on: ubuntu-latest
    name: "Deploy da aplicação"
    
    steps:
      - name: Verifica o repositório Git
        uses: actions/checkout@v2

      - name: Instala o node com a versão 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy para a Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}